# Generated by Django 3.2.4 on 2021-08-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mno', models.PositiveIntegerField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
